// AUTO-GENERATED by scripts/refresh-igdb-vocab.ts on 2026-05-14.
// DO NOT regenerate without committing the diff for review — the mechanics
// list (IGDB_MECHANICS) is hand-curated and a re-run will overwrite removals.
//
// To refresh: run scripts/refresh-igdb-vocab.ts, hand-edit the IGDB_MECHANICS
// set to drop noise, commit. See docs/superpowers/specs/2026-05-13-igdb-mechanics-design.md
// "Vocabulary" section for curation criteria.

export const IGDB_GAME_MODES: ReadonlySet<string> = new Set([
  "Single player",
  "Multiplayer",
  "Co-operative",
  "Split screen",
  "Massively Multiplayer Online (MMO)",
  "Battle Royale",
]);

export const IGDB_PLAYER_PERSPECTIVES: ReadonlySet<string> = new Set([
  "First person",
  "Third person",
  "Bird view / Isometric",
  "Side view",
  "Text",
  "Auditory",
  "Virtual Reality",
]);

export const IGDB_THEMES: ReadonlySet<string> = new Set([
  "Drama",
  "Non-fiction",
  "Sandbox",
  "Educational",
  "Kids",
  "Open world",
  "Warfare",
  "Party",
  "4X (explore, expand, exploit, and exterminate)",
  "Erotic",
  "Mystery",
  "Action",
  "Fantasy",
  "Science fiction",
  "Horror",
  "Thriller",
  "Survival",
  "Historical",
  "Stealth",
  "Comedy",
  "Business",
  "Romance",
]);

// Hand-curated subset of IGDB /keywords. Generated draft is the oldest
// 500 keywords (sort id asc) filtered to length <= 25 chars.
// Hand-edit to drop platform/engine names (Linux, Unity), pure genres (FPS),
// themes that overlap with IGDB_THEMES (Horror), subjective adjectives,
// and single-game proper nouns.
// Curated 2026-05-14: 498 → 151 entries. See docs/superpowers/specs/2026-05-13-igdb-mechanics-design.md § "Vocabulary".
export const IGDB_MECHANICS: ReadonlySet<string> = new Set([
  // --- Simulation sub-genres ---
  "space simulation",
  "life simulation",
  "simulated reality",
  "vehicle simulation",
  "flight simulator",
  "combat flight simulator",
  "train simulator",
  "tank simulator",
  "ship simulator",
  "racing simulator",
  "truck simulator",
  "mmorts",
  "simulation",

  // --- Combat / action sub-genres ---
  "rail shooter",
  "shoot 'em up",
  "shmup",
  "first person shooter",
  "run and gun",
  "bullet hell",
  "brawler",
  "street fighting",
  "action-adventure",
  "vehicular combat",
  "space combat",
  "space shooter",
  "naval",

  // --- Strategy / tactics ---
  "grand strategy",
  "real time tactics",
  "space strategy",
  "tower defense",
  "tycoon",
  "management",
  "micromanagement",
  "diplomacy",
  "god game",

  // --- Progression / RPG systems ---
  "roguelike",
  "permadeath",
  "procedural generation",
  "leveling",
  "grinding",
  "character customization",
  "upgradable weapons",
  "turn-based",
  "real-time",
  "jrpg",
  "crpg",
  "diablo-like",
  "metroidvania",
  "role playing",

  // --- Movement mechanics ---
  "parkour",
  "side-scrolling",
  "backtracking",

  // --- Narrative / structure ---
  "story driven",
  "choose your own adventure",
  "interactive fiction",
  "graphic adventure",
  "multiple endings",
  "multiple protagonists",
  "mission based",
  "episodic",
  "level editor",

  // --- Gameplay verbs / loop ---
  "crafting",
  "farming",
  "fishing",
  "hunting",
  "cooking",
  "gardening",
  "breeding",
  "collecting",
  "trading",
  "construction",
  "resource management",
  "exploration",
  "space exploration",
  "space mining",
  "investigation",
  "heist",
  "crime solving",
  "espionage",
  "photography",
  "minigames",
  "quick-time events",

  // --- Player count / online modes ---
  "pvp",
  "competitive",
  "online co-op",
  "asymmetric gameplay",

  // --- Combat modifiers ---
  "martial arts",
  "hand-to-hand combat",
  "swordplay",
  "archery",
  "summoning support",
  "bullet time",
  "squad based",
  "party-based combat",

  // --- Physics / world systems ---
  "physics",
  "gravity",
  "destruction",
  "time manipulation",
  "time travel",
  "psychic abilities",
  "magic",
  "occult",

  // --- Tone / setting flavors ---
  "post-apocalyptic",
  "dystopian",
  "cyberpunk",
  "steampunk",
  "futuristic",
  "dark fantasy",
  "gothic",
  "neo noir",
  "noir",
  "paranormal",
  "supernatural",
  "lovecraftian",
  "psychological horror",
  "psychological thriller",
  "psychological exploration",
  "wild west",
  "medieval",
  "alternate history",
  "parallel worlds",

  // --- Technology / creature types (gameplay elements) ---
  "mech",
  "robots",
  "androids",
  "cyborg",
  "kaiju",
  "giant monsters",
  "spaceship",

  // --- Card / board game adaptations ---
  "collectible card game",
  "boardgame adaptation",
  "chess",
  "shogi",
  "poker",
  "mahjong",
  "blackjack",

  // --- Protagonist / perspective types ---
  "female protagonist",
  "animal protagonist",
  "child protagonist",

  // --- Misc structural / meta mechanics ---
  "maze",
  "labyrinth",
  "hidden object",
  "match 3",
  "street racing",
  "time limit",
  "evolution",
  "pet raising",
  "virtual pet",
  "extreme sports",
  "treasure hunt",
  "underwater",
  "guitar playing",
]);

// ── Mood-affinity vocabulary bridge (Task 8, 2026-05-16) ─────────────
// `lib/recs/mood-affinity.ts` describes each mood with hyphenated /
// abbreviated affinity tokens (`life-sim`, `co-op`, `story-only`, …).
// Those tokens were authored against an imagined vocabulary and never
// reconciled with the REAL catalog, so an exact lowercased `Set.has()`
// match never fired against actual `games.mechanics` (curated IGDB,
// space-delimited — `life simulation`, `online co-op`, `story driven`)
// nor `games.genres` (RAWG names, mixed-case — `RPG`, `Casual`).
//
// These two maps are the ONLY canonicalization layer: an affinity token
// (or a catalog value) is canonicalized by lowercasing and looking it up
// here; if absent it canonicalizes to its own lowercased self. This keeps
// matching deterministic and is intentionally CONSERVATIVE — only tokens
// with a genuine real-term equivalent are mapped. Tokens with no catalog
// equivalent (`no-pressure`, `relaxing`, `cozy`, `skill-based`,
// `time-pressure`, `choices-matter`, `branching-narrative`, `voice-acted`,
// `twitch`, `idle`, `no-fail`, `single-player-only`, …) are deliberately
// LEFT OUT so they stay unmatched rather than forcing a wrong mapping
// that would mis-rank. Single-word IGDB terms that already matched
// pre-Task-8 (`permadeath`, `exploration`, `competitive`, `pvp`,
// `roguelike`, `simulation`) need NO entry — self-canonicalization
// preserves them (explicit no-regression test in mood-affinity.test.ts).
//
// Values are lowercased real terms drawn verbatim from IGDB_MECHANICS
// (mechanics) / the live RAWG `games.genres` distinct set (genres).

/** affinity mechanic token → real lowercased IGDB_MECHANICS term. */
export const MOOD_MECHANIC_CANONICAL: ReadonlyMap<string, string> = new Map([
  ["life-sim", "life simulation"],
  ["co-op", "online co-op"],
  // The catalog has no generic "online multiplayer" mechanic; `online co-op`
  // is its closest curated equivalent (pvp is a separate boost token).
  ["online-multiplayer", "online co-op"],
  ["story-only", "story driven"],
  ["narrative-only", "story driven"],
]);

/** affinity genre token → real lowercased RAWG `games.genres` name. */
export const MOOD_GENRE_CANONICAL: ReadonlyMap<string, string> = new Map([
  ["puzzle", "puzzle"],
  ["casual", "casual"],
  ["indie", "indie"],
  ["strategy", "strategy"],
  ["fighting", "fighting"],
  ["rpg", "rpg"],
  ["adventure", "adventure"],
  // RAWG has no "life sim"/"narrative"/"visual novel"/"roguelike"/"clicker"/
  // "runner"/"party" GENRE; `life-sim`/`mmo` get the closest RAWG genre.
  // (`life-sim`'s mechanic side maps to `life simulation` separately.)
  ["life-sim", "simulation"],
  ["mmo", "massively multiplayer"],
]);

/**
 * Canonicalize one mechanic string (an affinity token OR a `games.mechanics`
 * value) to a comparable lowercased form. Falls back to the lowercased input
 * when no alias exists — so already-real single-word terms and the real
 * catalog values both canonicalize to themselves and still compare equal.
 */
export function canonicalizeMechanicTerm(term: string): string {
  const lower = term.trim().toLowerCase();
  return MOOD_MECHANIC_CANONICAL.get(lower) ?? lower;
}

/** Genre counterpart of {@link canonicalizeMechanicTerm} (RAWG vocabulary). */
export function canonicalizeGenreTerm(term: string): string {
  const lower = term.trim().toLowerCase();
  return MOOD_GENRE_CANONICAL.get(lower) ?? lower;
}
