// AUTO-GENERATED by scripts/refresh-igdb-vocab.ts on 2026-05-14.
// DO NOT regenerate without committing the diff for review — the mechanics
// list (IGDB_MECHANICS) is hand-curated and a re-run will overwrite removals.
//
// To refresh: run scripts/refresh-igdb-vocab.ts, hand-edit the IGDB_MECHANICS
// set to drop noise, commit. See docs/superpowers/specs/2026-05-13-igdb-mechanics-design.md
// "Vocabulary" section for curation criteria.

export const IGDB_GAME_MODES: ReadonlySet<string> = new Set([
  "Single player",
  "Multiplayer",
  "Co-operative",
  "Split screen",
  "Massively Multiplayer Online (MMO)",
  "Battle Royale",
]);

export const IGDB_PLAYER_PERSPECTIVES: ReadonlySet<string> = new Set([
  "First person",
  "Third person",
  "Bird view / Isometric",
  "Side view",
  "Text",
  "Auditory",
  "Virtual Reality",
]);

export const IGDB_THEMES: ReadonlySet<string> = new Set([
  "Drama",
  "Non-fiction",
  "Sandbox",
  "Educational",
  "Kids",
  "Open world",
  "Warfare",
  "Party",
  "4X (explore, expand, exploit, and exterminate)",
  "Erotic",
  "Mystery",
  "Action",
  "Fantasy",
  "Science fiction",
  "Horror",
  "Thriller",
  "Survival",
  "Historical",
  "Stealth",
  "Comedy",
  "Business",
  "Romance",
]);

// Hand-curated subset of IGDB /keywords. Generated draft is the oldest
// 500 keywords (sort id asc) filtered to length <= 25 chars.
// Hand-edit to drop platform/engine names (Linux, Unity), pure genres (FPS),
// themes that overlap with IGDB_THEMES (Horror), subjective adjectives,
// and single-game proper nouns.
// Curated 2026-05-14: 498 → 151 entries. See docs/superpowers/specs/2026-05-13-igdb-mechanics-design.md § "Vocabulary".
export const IGDB_MECHANICS: ReadonlySet<string> = new Set([
  // --- Simulation sub-genres ---
  "space simulation",
  "life simulation",
  "simulated reality",
  "vehicle simulation",
  "flight simulator",
  "combat flight simulator",
  "train simulator",
  "tank simulator",
  "ship simulator",
  "racing simulator",
  "truck simulator",
  "mmorts",
  "simulation",

  // --- Combat / action sub-genres ---
  "rail shooter",
  "shoot 'em up",
  "shmup",
  "first person shooter",
  "run and gun",
  "bullet hell",
  "brawler",
  "street fighting",
  "action-adventure",
  "vehicular combat",
  "space combat",
  "space shooter",
  "naval",

  // --- Strategy / tactics ---
  "grand strategy",
  "real time tactics",
  "space strategy",
  "tower defense",
  "tycoon",
  "management",
  "micromanagement",
  "diplomacy",
  "god game",

  // --- Progression / RPG systems ---
  "roguelike",
  "permadeath",
  "procedural generation",
  "leveling",
  "grinding",
  "character customization",
  "upgradable weapons",
  "turn-based",
  "real-time",
  "jrpg",
  "crpg",
  "diablo-like",
  "metroidvania",
  "role playing",

  // --- Movement mechanics ---
  "parkour",
  "side-scrolling",
  "backtracking",

  // --- Narrative / structure ---
  "story driven",
  "choose your own adventure",
  "interactive fiction",
  "graphic adventure",
  "multiple endings",
  "multiple protagonists",
  "mission based",
  "episodic",
  "level editor",

  // --- Gameplay verbs / loop ---
  "crafting",
  "farming",
  "fishing",
  "hunting",
  "cooking",
  "gardening",
  "breeding",
  "collecting",
  "trading",
  "construction",
  "resource management",
  "exploration",
  "space exploration",
  "space mining",
  "investigation",
  "heist",
  "crime solving",
  "espionage",
  "photography",
  "minigames",
  "quick-time events",

  // --- Player count / online modes ---
  "pvp",
  "competitive",
  "online co-op",
  "asymmetric gameplay",

  // --- Combat modifiers ---
  "martial arts",
  "hand-to-hand combat",
  "swordplay",
  "archery",
  "summoning support",
  "bullet time",
  "squad based",
  "party-based combat",

  // --- Physics / world systems ---
  "physics",
  "gravity",
  "destruction",
  "time manipulation",
  "time travel",
  "psychic abilities",
  "magic",
  "occult",

  // --- Tone / setting flavors ---
  "post-apocalyptic",
  "dystopian",
  "cyberpunk",
  "steampunk",
  "futuristic",
  "dark fantasy",
  "gothic",
  "neo noir",
  "noir",
  "paranormal",
  "supernatural",
  "lovecraftian",
  "psychological horror",
  "psychological thriller",
  "psychological exploration",
  "wild west",
  "medieval",
  "alternate history",
  "parallel worlds",

  // --- Technology / creature types (gameplay elements) ---
  "mech",
  "robots",
  "androids",
  "cyborg",
  "kaiju",
  "giant monsters",
  "spaceship",

  // --- Card / board game adaptations ---
  "collectible card game",
  "boardgame adaptation",
  "chess",
  "shogi",
  "poker",
  "mahjong",
  "blackjack",

  // --- Protagonist / perspective types ---
  "female protagonist",
  "animal protagonist",
  "child protagonist",

  // --- Misc structural / meta mechanics ---
  "maze",
  "labyrinth",
  "hidden object",
  "match 3",
  "street racing",
  "time limit",
  "evolution",
  "pet raising",
  "virtual pet",
  "extreme sports",
  "treasure hunt",
  "underwater",
  "guitar playing",
]);
