/**
 * Pulls IGDB's vocabulary endpoints once and (optionally) writes the result
 * to lib/igdb/vocabulary.ts.
 *
 * Run:
 *   pnpm tsx --env-file=.env scripts/refresh-igdb-vocab.ts            # writes the file
 *   pnpm tsx --env-file=.env scripts/refresh-igdb-vocab.ts --print-only # prints + skips write
 *
 * Hand-curation: review the keyword section of the printed output. Drop
 * platform/engine names, pure-genre terms, themes that overlap with the
 * IGDB themes facet, and one-game noise (games_count < 50 is a useful
 * cutoff). The script suggests a draft based on a games_count >= 50 +
 * length <= 25-char heuristic; hand-edit the resulting file before
 * committing.
 *
 * Note: this script intentionally inlines the IGDB/Twitch HTTP calls rather
 * than importing from lib/igdb/client.ts or lib/igdb/twitch-oauth.ts. Both
 * of those modules carry `import "server-only"` which throws when loaded
 * outside the Next.js RSC runtime. The in-memory token fetch below is
 * equivalent for a one-shot CLI script.
 */
import { writeFile } from "node:fs/promises";

const IGDB_BASE = "https://api.igdb.com/v4";
const KEYWORDS_LIMIT = 500;
// IGDB /keywords has no games_count field. We sort by id asc (oldest entries
// first) as a proxy for "well-established / widely-used" keywords. The oldest
// 500 IDs cover the core genre/mechanics vocabulary; newer IDs tend to be
// single-game names and noise.
const KEYWORD_MAX_LEN = 25;

type Named = { name: string };

/** Fetch a Twitch client-credentials token (in-memory, not cached to DB). */
async function getTwitchToken(): Promise<string> {
  const clientId = process.env.IGDB_CLIENT_ID;
  const clientSecret = process.env.IGDB_CLIENT_SECRET;
  if (!clientId || !clientSecret) {
    throw new Error("IGDB_CLIENT_ID and IGDB_CLIENT_SECRET must be set in .env");
  }
  const params = new URLSearchParams({
    client_id: clientId,
    client_secret: clientSecret,
    grant_type: "client_credentials",
  });
  const res = await fetch(`https://id.twitch.tv/oauth2/token?${params.toString()}`, {
    method: "POST",
  });
  if (!res.ok) {
    const body = await res.text().catch(() => "<unreadable>");
    throw new Error(`Twitch token HTTP ${res.status}: ${body}`);
  }
  const payload = (await res.json()) as { access_token: string; expires_in: number };
  return payload.access_token;
}

/** Single IGDB query. */
async function igdbQuery<T>(
  clientId: string,
  token: string,
  endpoint: string,
  body: string,
): Promise<T> {
  const res = await fetch(`${IGDB_BASE}/${endpoint}`, {
    method: "POST",
    headers: {
      "Client-ID": clientId,
      Authorization: `Bearer ${token}`,
      "Content-Type": "text/plain",
    },
    body,
  });
  if (!res.ok) {
    const text = await res.text().catch(() => "<unreadable>");
    throw new Error(`IGDB HTTP ${res.status} on /${endpoint}: ${text.slice(0, 300)}`);
  }
  return (await res.json()) as T;
}

async function main() {
  const printOnly = process.argv.includes("--print-only");
  const clientId = process.env.IGDB_CLIENT_ID;
  if (!clientId) {
    throw new Error("IGDB_CLIENT_ID must be set in .env");
  }

  console.log("Fetching Twitch app-access token…");
  const token = await getTwitchToken();
  console.log("  token: ok");

  console.log("Fetching IGDB vocabulary…");
  const [modes, perspectives, themes, keywords] = await Promise.all([
    igdbQuery<Named[]>(clientId, token, "game_modes", "fields name; limit 50;"),
    igdbQuery<Named[]>(clientId, token, "player_perspectives", "fields name; limit 50;"),
    igdbQuery<Named[]>(clientId, token, "themes", "fields name; limit 50;"),
    igdbQuery<Named[]>(
      clientId,
      token,
      "keywords",
      `fields name; sort id asc; limit ${KEYWORDS_LIMIT};`,
    ),
  ]);

  console.log(`  modes:        ${modes.length}`);
  console.log(`  perspectives: ${perspectives.length}`);
  console.log(`  themes:       ${themes.length}`);
  console.log(`  keywords:     ${keywords.length} (oldest ${KEYWORDS_LIMIT} by id asc)`);

  // Draft mechanics list — heuristic filter before hand-curation.
  // No games_count field on IGDB /keywords; we use length <= KEYWORD_MAX_LEN
  // to drop obvious single-game proper-noun noise. Hand-curation removes the rest.
  const mechanicsDraft = keywords.filter((k) => k.name.length <= KEYWORD_MAX_LEN);

  console.log("\n=== KEYWORDS DRAFT (review for hand-curation) ===");
  for (const k of mechanicsDraft) {
    console.log(`  ${k.name}`);
  }
  console.log(`\nDraft size: ${mechanicsDraft.length}`);

  if (printOnly) {
    console.log("\n--print-only — skipping write");
    return;
  }

  const today = new Date().toISOString().slice(0, 10);
  const file = `// AUTO-GENERATED by scripts/refresh-igdb-vocab.ts on ${today}.
// DO NOT regenerate without committing the diff for review — the mechanics
// list (IGDB_MECHANICS) is hand-curated and a re-run will overwrite removals.
//
// To refresh: run scripts/refresh-igdb-vocab.ts, hand-edit the IGDB_MECHANICS
// set to drop noise, commit. See docs/superpowers/specs/2026-05-13-igdb-mechanics-design.md
// "Vocabulary" section for curation criteria.

export const IGDB_GAME_MODES: ReadonlySet<string> = new Set([
${modes.map((m) => `  ${JSON.stringify(m.name)},`).join("\n")}
]);

export const IGDB_PLAYER_PERSPECTIVES: ReadonlySet<string> = new Set([
${perspectives.map((p) => `  ${JSON.stringify(p.name)},`).join("\n")}
]);

export const IGDB_THEMES: ReadonlySet<string> = new Set([
${themes.map((t) => `  ${JSON.stringify(t.name)},`).join("\n")}
]);

// Hand-curated subset of IGDB /keywords. Generated draft is the oldest
// ${KEYWORDS_LIMIT} keywords (sort id asc) filtered to length <= ${KEYWORD_MAX_LEN} chars.
// Hand-edit to drop platform/engine names (Linux, Unity), pure genres (FPS),
// themes that overlap with IGDB_THEMES (Horror), subjective adjectives,
// and single-game proper nouns.
export const IGDB_MECHANICS: ReadonlySet<string> = new Set([
${mechanicsDraft.map((k) => `  ${JSON.stringify(k.name)},`).join("\n")}
]);
`;
  await writeFile("lib/igdb/vocabulary.ts", file, "utf8");
  console.log(`\nWrote lib/igdb/vocabulary.ts (${mechanicsDraft.length} mechanics — REVIEW + EDIT before committing)`);
}

void main().catch((err) => {
  console.error("Fatal:", err);
  process.exit(1);
});
